{{- if and (not .Values.slogr.existingSecret) .Values.slogr.apiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slogr-agent.fullname" . }}-api-key
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slogr-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.slogr.apiKey | quote }}
{{- end }}
